spring:
  profiles:
    active: file
  flyway:
    enabled: false
  security:
    user:
      name: user
      password: password

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG




