server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

invoicing-system:
  database: memory
