server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing-jpa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    enabled: false

invoicing-system:
  database: jpa
