spring:
  profiles:
    active: file
  flyway:
    enabled: false

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG




