spring:
  profiles:
    active: mongo
  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG




