package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class Car {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonIgnore
    @ApiModelProperty(value = "Car id (generated by application)", required = true, example = "1")
    private Integer id;

    @ApiModelProperty(value = "Car registration number", required = true, example = "SL 846259")
    private String registrationNumber;

    @ApiModelProperty(value = "Specifies whether company car is used for personal reasons", required = true, example = "true")
    private boolean privateExpense;
}
