package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class Invoice {

    @ApiModelProperty(value = "Invoice id (generated by application)", required = true, example = "1")
    private int id;

    @ApiModelProperty(value = "Date invoice was created", required = true)
    private LocalDate issueDate;

    @ApiModelProperty(value = "Company that bought the product/service", required = true)
    private Company buyer;

    @ApiModelProperty(value = "Company selling the product/service", required = true)
    private Company seller;

    @ApiModelProperty(value = "List of products/services", required = true)
    private List<InvoiceEntry> entries;

    public Invoice(LocalDate issueDate, Company buyer, Company seller, List<InvoiceEntry> entries) {
        this.issueDate = issueDate;
        this.buyer = buyer;
        this.seller = seller;
        this.entries = entries;
    }
}
