name: Building the Invoicing system - CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - task_*
  pull_request:
    branches:
      - master
      - task_*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify-test-coverage:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      -uses: actions/checkout@v2
      -name: Check test coverage
       run: ./gradlew check

  build:
    runs-on: windows-latest
    timeout-minutes: 10
    needs:
      - verify-test-coverage
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build